---
- name: Deploy Hampuff SMS Web Service
  hosts: hampuff_sms
  become: yes
  vars:
    app_name: hampuff-sms
    app_user: hampuff-sms
    app_group: hampuff-sms
    app_dir: "{{ deploy_path | default('/opt/hampuff-sms') }}"
    app_port: 15016
    python_version: "3.11"
    app_environment: "{{ app_environment | default('production') }}"
    app_domain: "{{ 'dev.hampuff.com' if app_environment == 'development' else 'www.hampuff.com' }}"
  vars_files:
    - group_vars/hampuff-sms/vault.yml
    
  handlers:
    - name: reload systemd
      systemd:
        daemon_reload: yes

    - name: restart hampuff-sms
      systemd:
        name: hampuff-sms
        state: restarted

  tasks:
    - name: Include tasks
      include_tasks: tasks/main.yml
