---
- name: Deploy Hampuff SMS Web Service
  hosts: pb_all
  become: yes
  vars:
    app_name: hampuff-sms
    app_user: hampuff-sms
    app_group: hampuff-sms
    app_dir: /opt/hampuff-sms
    app_port: 15015
    python_version: "3.9"
    
  handlers:
    - name: reload systemd
      systemd:
        daemon_reload: yes

    - name: restart hampuff-sms
      systemd:
        name: hampuff-sms
        state: restarted

  tasks:
    - name: Include tasks
      include_tasks: tasks/main.yml
